Embeds array for send message async
Discord-Net-Labs/Discord.Net-Labs pull request #181
Opened 2021-09-23 19:23 UTC by killerfrienddk

Since discord has added the support for it in the api I thought why not add it :)

2021-09-23 19:27 UTC, quinchs commented
See #129

2021-09-23 19:32 UTC, killerfrienddk commented
@quinchs Mine would not break preexisting peoples old SendMessageAsync that uses a single embed.

2021-09-23 19:57 UTC, quinchs commented
@d4n3436 thoughs?

2021-09-23 20:27 UTC, d4n3436 commented
It would be better to move the  single embed parameter to the end to keep consistency with other methods that also added embed array params (like #72)

Honestly I would just replace the single embed param with the embed array. It will be a breaking change but a better one, since the single embed param will have to be removed eventually.

2021-09-23 20:29 UTC, killerfrienddk commented
@d4n3436 This would allow for people not breaking their code if they wish to use the single one then they can it will simply add the single one to the array if the array is null.

2021-09-23 20:36 UTC, d4n3436 commented
> @d4n3436 This would allow for people not breaking their code if they wish to use the single one then they can it will simply add the single one to the array if the array is null.

Adding an extra parameter anywhere but at the end will be a breaking change anyway.
A better solution may be:

- Keep the embed param in the same place it is right now.
- Add the embed array param at the end.

This solution won't break anyone's code and will allow people to use the embed array param if they want to.

2021-09-23 20:37 UTC, killerfrienddk commented
True ill move them to the end.

2021-09-23 20:39 UTC, d4n3436 commented
Wait that was my idea 😐
nvm

2021-09-23 21:11 UTC, killerfrienddk commented
It is done @d4n3436 sorry I had no idea you had a pr, I would just have added the latter stuff to yours if I had known.

2021-09-24 08:42 UTC, MrCakeSlayer requested changes

2021-09-24 08:42 UTC, MrCakeSlayer commented on src/Discord.Net.Commands/ModuleBase.cs
> +        /// <param name="embeds">A array of <see cref="Embed"/>s to send with this response. Max 10</param>        /// <param name="allowedMentions">
Could you fix the comment lines :)

2021-09-24 08:56 UTC, MrCakeSlayer approved these changes

2021-09-24 09:10 UTC, quinchs approved these changes

2021-09-24 09:10 UTC, merged