Followup with file async warnings
Discord-Net-Labs/Discord.Net-Labs pull request #216
Opened 2021-10-03 18:31 UTC by killerfrienddk

2021-10-03 20:30 UTC, d4n3436 commented
The parameters `filePath`, `fileStream` and `fileName` shouldn't have a default value since they are not supposed to be null.

2021-10-03 20:43 UTC, d4n3436 commented
Another note, not related to this PR but should be done:
The method that uses a file path can be greatly simplified by using the one that uses the stream, like [SendFileAsync](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/release/3.x/src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs#L337-L343).

2021-10-03 20:44 UTC, killerfrienddk commented
Meaning that it will give people errors because they would have to change their inputs around.

2021-10-03 20:47 UTC, d4n3436 commented
> Meaning that it will give people errors because they would have to change their inputs around.

Yeah, that's the problem of not being consistent with other methods...

2021-10-03 20:48 UTC, killerfrienddk commented
Well the one that does not take a stream does not require the filename

2021-10-03 21:00 UTC, d4n3436 commented
> Well the one that does not take a stream does not require the filename

Yes, because the filename is taken from the file path.
There are 2 options we can take:

1. Keep the `filename` parameter, allowing to use a different name than the original from the file.
2. Remove the `filename` parameter and be consistent with `SendFileAsync`.

@quinchs thoughts?

2021-10-04 13:18 UTC, quinchs approved these changes

2021-10-04 13:18 UTC, quinchs commented on src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
> +            if (fileName != null && !string.IsNullOrEmpty(filePath))
Please use `Path.GetFileName(filePath);`

2021-10-04 13:19 UTC, quinchs commented
I would make the filename optional, the code for that would just be a `fileName ??= Path.GetFileName(filePath)`

2021-10-04 14:02 UTC, killerfrienddk commented
Alright I have done as suggested, how ever I have still kept the error check, because that when I looked in to GetFileName it did not seem to check for periods.

2021-10-04 14:04 UTC, quinchs commented
I mean we dont have to check for periods, the normal send file does not.

2021-10-04 14:07 UTC, killerfrienddk commented
I do think it is still a good idea to do so.

2021-10-04 14:08 UTC, killerfrienddk commented
Would you not want it to give an error if there is not extension?

2021-10-04 14:08 UTC, quinchs requested changes

2021-10-04 14:08 UTC, quinchs commented on src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
> +            if (fileName == null || fileName != null && !fileName.Contains('.')) throw new ArgumentException("Make sure that the file path has the file name in it with a period.");
Instead of saying "with a period." how about "With a valid file extension"?

2021-10-04 14:13 UTC, killerfrienddk commented
It has been done also added the checks to SendFileAsync.

2021-10-04 14:21 UTC, quinchs requested changes

2021-10-04 14:21 UTC, quinchs commented on src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
> +            if (filename == null || filename != null && !filename.Contains('.'))
wouldn't this need to be `filename == null || (filename != null && !filename.Contains('.'))` due to the OR statement

2021-10-04 14:23 UTC, killerfrienddk commented on src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
> +            if (filename == null || filename != null && !filename.Contains('.'))
It would fire on the first if it was null, so the second check does not need to have the not null check tbh.

2021-10-04 14:31 UTC, killerfrienddk commented on src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
> +            if (filename == null || filename != null && !filename.Contains('.'))
Also no it would not need to be (filename != null && !filename.Contains('.')))

2021-10-04 14:56 UTC, quinchs approved these changes

2021-10-04 14:56 UTC, merged

2021-10-04 18:03 UTC, d4n3436 commented
> It has been done also added the checks to SendFileAsync.

Extensions in files are not required. Discord allows files without extensions.

2021-10-04 18:14 UTC, killerfrienddk commented
> > It has been done also added the checks to SendFileAsync.
> 
> Extensions in files are not required. Discord allows files without extensions.

How in the world would it other ways know that it is a file, does it have a standard it makes it to?

2021-10-04 18:15 UTC, killerfrienddk commented
![image](https://user-images.githubusercontent.com/5002439/135902884-1080f7d7-d5be-41db-b0b2-9da7383d64a9.png)

2021-10-04 18:19 UTC, d4n3436 commented
That's for attachments inside embeds. It requires an image extension because the attachment is displayed using the ImageUrl property.

2021-10-04 18:19 UTC, killerfrienddk commented
Still have not been able to see anywhere on the discord api, where it says so.

2021-10-04 18:21 UTC, d4n3436 commented
I mean, it only appears in this section.
![image](https://user-images.githubusercontent.com/39978852/135903649-74345fee-40f3-4292-9cef-9a76b10393f1.png)

2021-10-04 18:23 UTC, killerfrienddk commented
Which file does not have an extension?

2021-10-04 18:26 UTC, d4n3436 commented
Wdym, any file can have or not have an extension.
![image](https://user-images.githubusercontent.com/39978852/135904284-add5e55e-099d-4e9e-b6a6-00ecdc43de43.png)