General cleanup
Discord-Net-Labs/Discord.Net-Labs pull request #223
Opened 2021-10-08 06:32 UTC by d4n3436

This PR makes a general cleanup of the codebase, specifically the files that are present in Discord.Net Labs but not in Discord.Net. 

The changes are the following:

- Fix null collections
- Fix typos
- Fix formatting
- Fix `ThreadMember` `Presence` property not being deserialized due to a typo
- Fix unused `RequestOptions` in `GetActiveThreadsAsync`
- Use `Array.Empty` instead of zero-length arrays
- Use more specific exceptions
- Use method group
- Use computed properties
- Use conditional access
- Use `var`
- Use `??` and `??=`
- Use switch expressions
- Use expression body in getters and setters
- Use `Async` suffix
- Remove redundancies
- Remove trailing commas
- Remove unreachable code
- Remove unnecessary usings, whitespace, parentheses, etc
- Other minor changes

This PR doesn't have any breaking changes, except the change of the type of exceptions that are thrown in some parts.

2021-10-08 11:52 UTC, SylveonDeko commented
That's a lot.

2021-10-08 16:49 UTC, quinchs requested changes

2021-10-08 16:49 UTC, quinchs commented on src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
> +                    throw new ArgumentNullException(nameof(value));
Are you sure this is correct? aren't the parameters `message`, `parameter`

2021-10-08 16:49 UTC, quinchs commented on src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
> +                    throw new ArgumentNullException(nameof(value));
Same comment as above

2021-10-08 17:15 UTC, d4n3436 commented on src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
> +                    throw new ArgumentNullException(nameof(value));
Yes, the parameter here is actually `value` and not `Name`.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof

The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.-ctor?view=net-5.0#System_ArgumentNullException__ctor_System_String_) also say that the single param of the constructor of `ArgumentNullException` is for the name of the parameter and not for the message.

I can bring back the message to make it clearer.

2021-10-09 05:33 UTC, quinchs commented on src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
> +                    throw new ArgumentNullException(nameof(value));
I would add the error message

2021-10-09 05:54 UTC, d4n3436 commented on src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOption.cs
> +                    throw new ArgumentNullException(nameof(value));
Done.

2021-10-09 05:54 UTC, d4n3436 commented on src/Discord.Net.Core/Entities/Interactions/Message Components/ComponentBuilder.cs
> +                    throw new ArgumentNullException(nameof(value));
Done

2021-10-09 06:11 UTC, merged