Modal Support
Discord-Net-Labs/Discord.Net-Labs pull request #337
Opened 2021-12-02 02:05 UTC by CottageDwellingCat

This a incomplete PR adding support for modals; it is currently undocumented and does not support `RestInteractions` and sharded clients.
TODO :
 - [ ] Rest Interactions
 - [ ] Sharded Clients
 - [ ] Docs + Examples
 - [ ] Interaction Service
 - [x] Socket Interactions
 - [x] Socket Clients

How it works:
```cs
client.SlashCommandExecuted += async x =>
{
	ModalBuilder builder = new ModalBuilder()
		.WithCustomId("modal_id")
		.WithTitle("title")
		.AddTextInput(new TextInputBuilder("label", TextInputStyle.Short, "text_id", "placeholder", 1, 20))
		.AddTextInput(new TextInputBuilder("label-two", TextInputStyle.Paragraph, "text_id_2", "placeholder_2", maxLength: 200));
	Modal modal = builder.Build();
	await x.RespondWithModalAsync(modal, RequestOptions.Default);
};
```
```cs
client.ModalSubmitted += async x => 
	await x.RespondAsync($"Your first answer was {x.Data.Components.First().Value}", ephemeral:true);
```

2021-12-23 17:59 UTC, lhjt requested changes

2021-12-23 17:59 UTC, lhjt commented on docs/guides/interactions/modals/01-getting-started.md
> +| `placeholder` | Sets the inputs placeholder.               |
```suggestion
| `label`       | Sets the input's label.                    |
| `customId`    | Sets the input's custom id.                |
| `style`       | Sets the input's style.                    |
| `placeholder` | Sets the input's placeholder.              |
```

2021-12-23 17:59 UTC, lhjt commented on docs/guides/interactions/modals/01-getting-started.md
> +| `WithCustomId`  | Sets the modals custom id.                |
```suggestion
| `WithTitle`     | Sets the modal's title.                   |
| `WithCustomId`  | Sets the modal's custom id.               |
```

2021-12-23 17:59 UTC, lhjt commented on docs/guides/interactions/modals/02-text-input.md
> +The simplest text input can build with:
```suggestion
The simplest text input can be built with:
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/InteractionResponseType.cs
> +        ///     Respond by showing the user a model.
```suggestion
        ///     Respond by showing the user a modal.
```

Potentially?

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
> +        /// <param name="required">The components required value.</param>
```suggestion
        /// <param name="label">The component's label.</param>
        /// <param name="style">The component's style.</param>
        /// <param name="customId">The component's custom id.</param>
        /// <param name="placeholder">The component's placeholder.</param>
        /// <param name="minLength">The component's minimum length.</param>
        /// <param name="maxLength">The component's maximum length.</param>
        /// <param name="required">The component's required value.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentType.cs
> +        ///     An interaction sent when a model is submitted.
```suggestion
        ///     An interaction sent when a modal is submitted.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/MessageComponents/TextInputComponent.cs
> +        ///     Gets the label of the component, this is the text shown above it.
```suggestion
        ///     Gets the label of the component - this is the text shown above it.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/MessageComponents/TextInputComponent.cs
> +        ///     Gets the minimum lenght of the inputed text.
```suggestion
        ///     Gets the minimum length of the inputted text.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/MessageComponents/TextInputComponent.cs
> +        ///     Gets the maximum length of the inputed text.
```suggestion
        ///     Gets the maximum length of the inputted text.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/MessageComponents/TextInputComponent.cs
> +        ///     Gets the default value of the component
```suggestion
        ///     Gets the default value of the component.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     Gets or sets the components in the model.
```suggestion
        ///     Gets or sets the components in the modal.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     Gets or sets the models title.
```suggestion
        ///     Gets or sets the modal's title.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     Gets or sets the models custom id.
```suggestion
        ///     Gets or sets the modal's custom id.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     Creates a new instance
```suggestion
        ///     Creates a new instance.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        /// <param name="components">The modals components.</param>
```suggestion
        /// <param name="title">The modal's title.</param>
        /// <param name="customId">The modal's customId.</param>
        /// <param name="components">The modal's components.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     Sets the current builders title.
```suggestion
        ///     Sets the current builder's title.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     Sets the current builders custom id.
```suggestion
        ///     Sets the current builder's custom id.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        /// <param name="style">The inputs style.</param>
```suggestion
        /// <param name="customId">The input's custom id.</param>
        /// <param name="label">The input's label.</param>
        /// <param name="placeholder">The input's placeholder text.</param>
        /// <param name="minLength">The input's minimum length.</param>
        /// <param name="maxLength">The input's maximum length.</param>
        /// <param name="style">The input's style.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        /// <returns>The current builder</returns>
```suggestion
        /// <returns>The current builder.</returns>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     The max amount of rows a <see cref="ModalComponent"/> can have.
```suggestion
        ///     The max number of rows a <see cref="ModalComponent"/> can have.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     If the row cannot accept the component then it will add it to a row that can.
```suggestion
        ///     If the row cannot accept the component, it will add it to a row that can.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        /// <param name="style">The inputs style.</param>
```suggestion
        /// <param name="customId">The input's custom id.</param>
        /// <param name="label">The input's label.</param>
        /// <param name="placeholder">The input's placeholder text.</param>
        /// <param name="minLength">The input's minimum length.</param>
        /// <param name="maxLength">The input's maximum length.</param>
        /// <param name="style">The input's style.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
> +        ///     If the row cannot accept the component then it will add it to a row that can.
```suggestion
        ///     If the row cannot accept the component, it will add it to a row that can.
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Interactions/Attributes/Commands/ModalInteractionAttribute.cs
> +    ///     Create a Modal interaction handler, CustomId represents
```suggestion
    ///     Create a Modal interaction handler. CustomId represents
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Interactions/Attributes/Commands/ModalInteractionAttribute.cs
> +    ///     CustomID supports a Wild Card pattern where you can use the <see cref="InteractionServiceConfig.WildCardExpression"/> to match a set of CustomIDs.
> CustomID

Is there going to be consistency between the naming of this property? (i.e. `CustomID` vs `CustomId`)

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Interactions/Attributes/Commands/ModalTextInputAttribute.cs
> +}
Missing newline? Have you run formatting on all your modified files?

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Interactions/InteractionService.cs
> +        ///     Occurs when a Modal command is executed.
> Modal 

Are we going to have some consistency around the naming? (i.e. `Modal` vs `modal` when used within docs)

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Rest/Entities/Interactions/Modals/RestModal.cs
> +        /// <param name="embeds">A array of embeds to send with this response. Max 10.</param>
```suggestion
        /// <param name="embeds">An array of embeds to send with this response. Max 10.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Rest/Entities/Interactions/Modals/RestModal.cs
> +        /// <param name="embeds">A array of embeds to send with this response. Max 10.</param>
```suggestion
        /// <param name="embeds">An array of embeds to send with this response. Max 10.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Rest/Entities/Interactions/Modals/RestModal.cs
> +        /// <param name="embeds">A array of embeds to send with this response. Max 10.</param>
```suggestion
        /// <param name="embeds">An array of embeds to send with this response. Max 10.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.Rest/Entities/Interactions/Modals/RestModal.cs
> +        /// <param name="embeds">A array of embeds to send with this response. Max 10.</param>
```suggestion
        /// <param name="embeds">An array of embeds to send with this response. Max 10.</param>
```

2021-12-23 17:59 UTC, lhjt commented on src/Discord.Net.WebSocket/Entities/Interaction/Modals/SocketModal.cs
> +    ///     Represents a user submitted <see cref="Discord.Modal"/> received via GateWay.
```suggestion
    ///     Represents a user submitted <see cref="Discord.Modal"/> received via Gateway.
```

Unsure of the capitalisation of the `w`?

2021-12-24 12:18 UTC, CottageDwellingCat commented
@lhjt thanks for taking the time to find some small grammatical errors in this pr; I really appreciate it. In it's current state the pr is not ready to be reviewed and as such it is marked as a draft. I opened the pr to provide a (more) easy way to give technical and implementation feedback on modals (especially the interaction service components). The following things need to happen before it is ready to review:
- Redo most inline docs to be more consistent with the rest of labs
- Rewrite the docs to be more consistent with the current style
- Add more validations for component builder fields and fix a few small null check related bugs I found well testing
- Finish implementing the interaction service
Because the code in this pr is clearly not ready to see the light of day I will close it, and continue to work on the branch in my repo. I will reopen the pr when it is fully ready to be reviewed and merged. Again, thank you for taking the time to look at my pr, and I apologize sincerely for the communication failures on my part.

2021-12-24 12:18 UTC, closed without merging

2021-12-24 12:23 UTC, lhjt commented
@CottageDwellingCat Oh yeah, absolutely no worries at all - I accidentally started reviewing it yesterday when I was going through the PRs on this repository and didn't recognise at the time that this was PR was a draft (error on my end - sorry about that)

> I apologize sincerely for the communication failures on my part

No worries at all and I feel like this is more of an error on my end; please feel free to reopen a PR in draft form with a checklist or similar if you would like and I'll take extra care next time to leave draft PRs as they are :+1: