Fixed applications not containing the TOS and Privacy strings.
Discord-Net-Labs/Discord.Net-Labs pull request #382
Opened 2021-12-18 00:26 UTC by FeroxFoxxo

## Fixed Application Modal
This is a PR fixing the application modal. It adds two fields, the TOS and Privacy Policy, fields that are in Discord's API but not DNet's.

2021-12-18 03:49 UTC, quinchs approved these changes

2021-12-18 03:49 UTC, quinchs commented on src/Discord.Net.Core/Entities/IApplication.cs
> +
Remove newline

2021-12-18 03:49 UTC, quinchs commented on src/Discord.Net.Rest/API/Common/Application.cs
>          public Optional<string[]> Tags { get; set; }
Can you add a `[JsonProperty("tags")]` above this

2021-12-18 03:51 UTC, quinchs requested changes
mean't to request changes

2021-12-18 10:17 UTC, FeroxFoxxo reviewed
Fixed all the issues given and added documentation for flags rather than removing the new line.

2021-12-19 03:02 UTC, quinchs approved these changes

2021-12-19 03:02 UTC, merged