Display name support for enum type converter
Discord-Net-Labs/Discord.Net-Labs pull request #407
Opened 2021-12-27 21:19 UTC by XenotropicDev

This PR adds basic support for enum's that have been decorated with the `DisplayAttribute` from `System.ComponentModel.DataAnnotations`.

I went with DisplayAttribute over other options because a lot of peoples enums might already be using this attribute from things like MVC, and it has support for localization. However doing so requires changing the project references to include the annotations library for the net461, and netstandard tagets (support is included in the core.app package for net5+). So if it would be better to use a custom attribute to avoid adding this package please let me know and I can modify the pull request.

2021-12-27 21:33 UTC, lhjt approved these changes
Spelling + grammar lgtm

2021-12-27 22:21 UTC, Cenngo commented
not sure if adding a dependency just to use one attribute is ideal. I think creating a custom attribute for this is better.

2021-12-27 23:24 UTC, XenotropicDev commented
> not sure if adding a dependency just to use one attribute is ideal. I think creating a custom attribute for this is better.

Sounds good to me, I will update the PR with a custom attribute class instead.

2021-12-28 01:09 UTC, lhjt approved these changes

2021-12-28 01:10 UTC, XenotropicDev commented
I updated the PR to no longer include any new dependencies, and added an internal attribute `ChoiceDisplayAttribute`.

Please re-review.

2021-12-28 07:57 UTC, Cenngo requested changes
it looks good.

2021-12-28 07:57 UTC, Cenngo commented on src/Discord.Net.Interactions/Attributes/EnumChoiceAttribute.cs
> +    /// </summary>
Can you add a remark here mentioning that this attribute only works with the default enum TypeConverter and not with custom ones.

2021-12-28 15:09 UTC, Cenngo approved these changes

2021-12-29 20:23 UTC, MrCakeSlayer approved these changes

2021-12-29 20:47 UTC, quinchs approved these changes

2021-12-29 20:48 UTC, merged