Add command search methods
Discord-Net-Labs/Discord.Net-Labs pull request #414
Opened 2022-01-10 21:33 UTC by Cenngo

This PR adds methods for exposing the command search logic of the Interaction Service

2022-01-10 21:42 UTC, Rozen4334 commented on src/Discord.Net.Interactions/InteractionService.cs
> +        ///     The search result.
Maybe note what type of search result is returned to stay consistent?

2022-01-10 21:42 UTC, Rozen4334 commented on src/Discord.Net.Interactions/InteractionService.cs
> +        ///     Search the loaded slash commands using a <see cref="IAutocompleteInteraction"/>.
What does 'loaded' imply, maybe change to 'registered' to match the naming of other methods in the service?

2022-01-10 21:43 UTC, Rozen4334 requested changes

2022-01-10 21:43 UTC, Rozen4334 commented on src/Discord.Net.Interactions/InteractionService.cs
> +        /// <returns></returns>
No return comment present?

2022-01-11 07:31 UTC, Cenngo commented
@Rozen4334 made the changes to the inline docs. take a look

2022-01-11 07:37 UTC, quinchs approved these changes

2022-01-11 07:38 UTC, quinchs commented
Waiting on Rozens review

2022-01-11 08:14 UTC, Rozen4334 approved these changes
lgtm

2022-01-11 08:14 UTC, merged