User locale in interactions
Discord-Net-Labs/Discord.Net-Labs pull request #415
Opened 2022-01-11 01:07 UTC by drobbins329

Adds UserLocale and GuildLocale optional strings in the JSON converters for Interactions

2022-01-11 07:44 UTC, quinchs commented
Can you add this property to the interaction classes, ex `SocketInteraction` and `RestInteraction`

2022-01-11 22:01 UTC, drobbins329 commented
Added in SocketInteraction, RestInteraction and IDiscordInteraction. Tested both User and Guild locale string outputs in guild. Both confirmed.

2022-01-11 22:54 UTC, quinchs requested changes

2022-01-11 22:54 UTC, quinchs commented on src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
> +        /// The preferred locale of the invoking User.
Add tab indenting to summaries

2022-01-11 22:54 UTC, quinchs commented on src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
> +        /// The preferred locale of the invoking User.
Shouldn't this be `/// <inheritdoc/>`

2022-01-11 22:54 UTC, quinchs commented on src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
> +        /// The preferred locale of the guild this interaction was executed in. <see cref="null"/> if not executed in a guild.
Shouldn't this be `/// <inheritdoc/>`

2022-01-11 22:54 UTC, quinchs commented on src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
> +        /// The preferred locale of the invoking User.
Shouldn't this be `/// <inheritdoc/>`

2022-01-11 22:54 UTC, quinchs commented on src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
> +        /// The preferred locale of the guild this interaction was executed in. <see cref="null"/> if not executed in a guild.
Shouldn't this be `/// <inheritdoc/>`

2022-01-11 23:02 UTC, drobbins329 commented on src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
> +        /// The preferred locale of the invoking User.
done

2022-01-12 00:12 UTC, quinchs approved these changes

2022-01-12 00:12 UTC, merged